### PR TITLE
Updated as advised in #1

### PR DESCRIPTION
**Pull request by ghost**
Here is the fork.

I like how ivy looks with the highilight face!

### CODE REVIEW

**Comment by bkruczyk** [comment]
There is a misplaced paren on line 216 causing theme failing to load.

Please amend author and message (typo) of sshbio/badwolf-emacs@f8af4290d4ed78728663262db4f7ba80e259c107.

**Comment by ghost** [comment]
Oh, sorry for this! I fixed it.

Such trouble for such a small change it was!

**Comment by bkruczyk** [comment]
Please amend author and message of `f8af429` or better squash your commits into one.

**Comment by ghost** [comment]
I'm still a beginner with git, and this may require patience to you,  Thank you for this, but I hope that it is not too much annoying to train someone to git for a small change like this.

I did my best to make it clean on the fork.

**Comment by bkruczyk** [comment]
It's a normal thing and there's no need to be apologetic :)
If you're interested check prelude's [contribution guide](https://github.com/bbatsov/prelude/blob/master/CONTRIBUTING.md#pull-requests) for general guidelines on pull requests.

**Comment by ghost** [comment]
At least I can be grateful a bit. I'm having a look at it, it is good a resource for me.

**Pull request merged**
